#define GLM_ENABLE_EXPERIMENTAL
#include "Host.h"

// --- Include System Implementations for Single Translation Unit Build ---
#include "BaseEntity.cpp"
#include "BaseSystem/SpawnSystem.cpp"
#include "BaseSystem/CollisionSystem.cpp"
#include "BaseSystem/WalkModeSystem.cpp"
#include "BaseSystem/GravitySystem.cpp"
#include "BaseSystem/SkyboxSystem.cpp" // <-- ADD THIS LINE
#include "BaseSystem/KeyboardInputSystem.cpp"
#include "BaseSystem/MouseInputSystem.cpp"
#include "BaseSystem/UAVSystem.cpp"
#include "BaseSystem/AudioSystem.cpp"
#include "BaseSystem/SoundtrackSystem.cpp"
#include "BaseSystem/UIStampingSystem.cpp"
#include "BaseSystem/DawStateSystem.cpp"
#include "BaseSystem/MicrophoneBlockSystem.cpp"
#include "BaseSystem/RayTracedAudioSystem.cpp"
#include "BaseSystem/SoundPhysicsSystem.cpp"
#include "BaseSystem/AudioRayVisualizerSystem.cpp"
#include "BaseSystem/PinkNoiseSystem.cpp"
#include "BaseSystem/AudicleSystem.cpp"
#include "BaseSystem/CameraSystem.cpp"
#include "BaseSystem/ChunkSystem.cpp"
#include "BaseSystem/FaceCullingSystem.cpp"
#include "BaseSystem/GreedyMeshingSystem.cpp"
#include "BaseSystem/RenderSystem.cpp"
#include "BaseSystem/CloudSystem.cpp"
#include "BaseSystem/AuroraSystem.cpp"
#include "BaseSystem/VolumeFillSystem.cpp"
#include "BaseSystem/GlyphSystem.cpp"
#include "BaseSystem/DebugHudSystem.cpp"
#include "BaseSystem/DebugWireframeSystem.cpp"
#include "BaseSystem/PerfSystem.cpp"
#include "BaseSystem/FontSystem.cpp"
#include "BaseSystem/BlockSelectionSystem.cpp"
#include "BaseSystem/BlockChargeSystem.cpp"
#include "BaseSystem/BuildSystem.cpp"
#include "BaseSystem/StructurePlacementSystem.cpp"
#include "BaseSystem/StructureCaptureSystem.cpp"
#include "BaseSystem/HUDSystem.cpp"
#include "BaseSystem/ExpanseBiomeSystem.cpp"
#include "BaseSystem/TerrainGenerationSystem.cpp"
#include "BaseSystem/TreeGenerationSystem.cpp"
#include "BaseSystem/UIScreenSystem.cpp"
#include "BaseSystem/DawLaneSystem.cpp"
#include "BaseSystem/ComputerCursorSystem.cpp"
#include "BaseSystem/ButtonSystem.cpp"
#include "BaseSystem/RegistryEditorSystem.cpp"
#include "BaseSystem/BootSequenceSystem.cpp"
#include "BaseSystem/ChucKSystem.cpp"
#include "BaseSystem/BlockTextureSystem.cpp"
#include "Host/HostShader.cpp"
#include "Host/HostUtilities.cpp"
#include "Host/Startup.cpp"
#include "Host/HostInput.cpp"
#include "Host/HostLoader.cpp"
#include "Host/Host.cpp"

int main() {
    Host cardinal;
    cardinal.run();
    return 0;
}
